### ISSUE TITLE
当前版本支持ROS控制吗

### ISSUE THREAD

**Issue by Sunchanghao** [RuPingCen/mick_robot_chassis#2]
您好 
感谢分享
我想用这个驱动程序，然后通过ROS对底盘控制，这个项目目前有支持ROS吗
谢谢！

**Comment by RuPingCen** [comment]
支持ROS控制的，对应的ROS节点包可以从下面的链接下载 https://github.com/RuPingCen/mick_robot/tree/master/mick_bringup
